### ISSUE TITLE
Question: is there a way to check if user is impersonated in controller

### ISSUE THREAD

**Issue by dualznz** [OctopyID/LaraPersonate#12]
Ho,

Love the package, i was wondering if there is a way to check if a user is being impersonated so then certain features of the application can be disabled, eg: login tracking

I am using the ui that you have built to impersonate user.

**Comment by SupianIDz** [comment]
Hi, sorry for the long reply. You can check the condition whether you are in impersonation or not by 

```php
app('impersonate')->isInImpersonation()
```

**Comment by dualznz** [comment]
cool, thanks just what i needed.
