### ISSUE TITLE
Issue with projects that stored in a sub-folder

### ISSUE THREAD

**Issue by NikarashiHatsu** [OctopyID/LaraPersonate#13]
Hi, before I get to the issue, I want to thank you for this package. Your package save me a lot of time.

The package works great if I used it directly on domain-level, but it broke when the project is in a sub-folder. To clarify my point, here's some diagram:

```
https://some-domain.com/                <-- This works just fine
https://some-domain.com/root-project    <-- This won't work
```

After un-minify the JavaScript file, I had to change the `t.select2.ajax`, `t.on('change')`, and `s.on('click')`. If un-minified, these codes are placed on line 33, 61, 64 respectively. Here's the code example I change:

```diff
t.select2({
    theme: "impersonate",
    ajax: {
-       url: "/impersonate/users",
+       url: "/root-project/impersonate/users",
        dataType: "JSON",
        method: "GET",
        delay: impersonate.config.delay,
        data: function (e) {
            return { search: e.term };
        },
        processResults: function (e) {
            return {
                results: i().map(e, function (e) {
                    return { id: e.key, text: e.val };
                }),
            };
        },
    },
}),
t.select2("open"),
t.select2("close"),
e.click(function () {
    r.toggleClass("impersonate-border"),
        e.find("img").toggleClass("impersonate-animate"),
        impersonate.active ? e.addClass("impersonate-toggle-active") : e.toggleClass("impersonate-toggle-active"),
        n.toggle("fast", function () {
            n.toggleClass("impersonate-content-toggled");
        }),
        impersonate.active ? (r.addClass("impersonate-wrapper-active"), n.addClass("impersonate-content-active")) : (r.addClass("impersonate-wrapper-non-active"), n.addClass("impersonate-content-non-active"));
}),
t.on("change", function () {
-     o("/impersonate/login", JSON.stringify({ user: this.value }));
+     o("/root-project/impersonate/login", JSON.stringify({ user: this.value }));
}),
s.on("click", function () {
-     o("/impersonate/leave", {});
+     o("/root-project/impersonate/leave", {});
});
```

I hope that explains the issue and could be fixed soon.
Best regards.

**Comment by SupianIDz** [comment]
> ```
> https://some-domain.com/                <-- This works just fine
> https://some-domain.com/root-project    <-- This won't work
> ```

If you set your project in a subdirectory, is the `APP_URL` in env something like `https://some-domain.com/root-project` ?

**Comment by SupianIDz** [comment]
I'll fix it ASAP

**Comment by SupianIDz** [comment]
@NikarashiHatsu It should work on version v3.0.2, 
```bash
composer require octopyid/laravel-impersonate:v3.0.2
```
don't forget to set `APP_URL`

**Comment by NikarashiHatsu** [comment]
> > ```
> > https://some-domain.com/                <-- This works just fine
> > https://some-domain.com/root-project    <-- This won't work
> > ```
> 
> If you set your project in a subdirectory, is the `APP_URL` in env something like `https://some-domain.com/root-project` ?

I definitely did this.

> @NikarashiHatsu It should work on version v3.0.2, 
> ```bash
> composer require octopyid/laravel-impersonate:v3.0.2
> ```
> don't forget to set `APP_URL`

Thanks for the fix, I'll try the newest update.

**Comment by NikarashiHatsu** [comment]
Hi, I updated the package version on my project, and I couldn't find the configuration related to the route.

By modifying the `APP_URL`, it simply won't work, so I did a small code exploration a little bit and added this line to the `config/impersonate.php`:

```diff
<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Impersonation Interface
    |--------------------------------------------------------------------------
    | You can override the value by setting enable to true or false instead of null.
    |
    */
    'enabled' => env('IMPERSONATE_ENABLED', true),
-                             
+   'route' => env('APP_URL'),
```

The code `route` key was not documented on the `Readme.md` so I'm not sure if I did the right thing or no. I suggest you to update the documentation as well. Now the project is running smoothly without any issue so I think it is safe to close this issue.

But I suggest you to update the documentation a bit, so people with similar issue could fix it as soon as they noticed it 👀.

**Comment by SupianIDz** [comment]
> By modifying the `APP_URL`, it simply won't work, so I did a small code exploration a little bit and added this line to the `config/impersonate.php`:
> 
> ```diff
> <?php
> 
> return [
>     /*
>     |--------------------------------------------------------------------------
>     | Impersonation Interface
>     |--------------------------------------------------------------------------
>     | You can override the value by setting enable to true or false instead of null.
>     |
>     */
>     'enabled' => env('IMPERSONATE_ENABLED', true),
> -                             
> +   'route' => env('APP_URL'),
> ```
> 

No need to add configuration, you only need to change the `.env`.

Don't forget to delete `public/vendor/octopy` and republish assets by 
```
artisan vendor:publish --provider="Octopy\Impersonate\ImpersonateServiceProvider"
```

**Comment by SupianIDz** [comment]
@NikarashiHatsu 
```diff
<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Impersonation Interface
    |--------------------------------------------------------------------------
    | You can override the value by setting enable to true or false instead of null.
    |
    */
    'enabled' => env('IMPERSONATE_ENABLED', true),
-                             
+   'route' => env('APP_URL'),
```

This code shouldn't be necessary, because `route` isn't used anywhere. i took it directly from `app.url` which is from `APP_URL` in `.env`

**Comment by NikarashiHatsu** [comment]
Oh right, I didn't republish the vendor assets.
Thanks a lot for your guidance,
