### ISSUE TITLE
ADMIN ONLY CAN IMPERSONATE

### ISSUE THREAD

**Issue by resujentoezequiel** [OctopyID/LaraPersonate#17]
Good day,

How can I show the impersonation function to the admin role only?

Thank you

**Comment by SupianIDz** [comment]
Hi @resujentoezequiel [Defining Limitation](https://github.com/OctopyID/LaraPersonate#311-defining-limitation)

**Comment by resujentoezequiel** [comment]
Where in the limitation can the admin role only see the impersonate function?

**Comment by resujentoezequiel** [comment]
**How can I set multiple impersonated?**

$authorization->impersonator(function (User $user) {
    return $user->user_role == "0";
});

$authorization->impersonated(function (User $user) {
    $a = array('1','2');
    return array_key_exists($user->user_role, $a);
});
