### ISSUE TITLE
Control who can impersonate and who can be impersonated

### ISSUE THREAD

**Issue by wh5a** [OctopyID/LaraPersonate#2]
Thanks for providing the package. It's really easy to install.
Can you add some access control, so that only admin can impersonate other users? Sort of like what another package supports: https://github.com/404labfr/laravel-impersonate#defining-impersonation-authorization

**Comment by SupianIDz** [comment]
@wh5a sure, i'll update this package ASAP.

**Comment by SupianIDz** [comment]
@wh5a hi, package with control added recently, please read the [README.md](https://github.com/OctopyID/LaraPersonate/blob/main/README.md)

**Comment by wh5a** [comment]
Thank you!
