### ISSUE TITLE
After a user change via LaraPersonate, I return every time to the login page

### ISSUE THREAD

**Issue by happytodev** [OctopyID/LaraPersonate#20]
Hello,

I tried your package.

The installation was ok => I saw the logo in the bottom right of my page. OK

But when I choose a different user, I return every time to the login page.

Little precision, I use Jetstream.

Do you have an idea of what's wrong on my side please ?

Thank you for your time.

**Comment by SupianIDz** [comment]
Hi @happytodev 

What type of Laravel Jetstream are you using? Vue with Inertia or Livewire?

**Comment by happytodev** [comment]
Hello @SupianIDz 

Thank you for your answer, here my details on my app :

1. I installed the last version composer require octopyid/laravel-impersonate:^4
2. Laravel Jetstream is with Livewire

Hope it helps ;-)

**Comment by SupianIDz** [comment]
confirmed, possibly due to different login mechanisms on Jetstream.

I'll find a way to fix it.

**Comment by happytodev** [comment]
> confirmed, possibly due to different login mechanisms on Jetstream.
> 
> I'll find a way to fix it.

Thanks !

**Comment by SupianIDz** [comment]
can you try `composer require octopyid/laravel-impersonate:^4.1` ?

**Comment by happytodev** [comment]
Hello, sorry for my late answer.

This fix the bug.

Be carreful to the little typo :

```shell
composer require octopyid/laravel-impersonate:^4.0.1
```

4.0.1 instead of 4.1 ;-)

Thank you for the help on this.

**Comment by SupianIDz** [comment]
glad to hear it.
