### ISSUE TITLE
Call to undefined method Octopy\Impersonate\Impersonate::isInImpersonation()

### ISSUE THREAD

**Issue by MCKLtech** [OctopyID/LaraPersonate#25]
**Describe the bug**

It seems app() and impersonate() are not registered/working e.g. 

```
app('impersonate')->isInImpersonation()
```

and

```
impersonate()
```
Do not appear to be working as they will throw an error such as: Call to undefined method Octopy\Impersonate\Impersonate::isInImpersonation()

But the following does work:

```
auth()->user()->impersonate($user);
```

 - PHP Version 8.2
 - Laravel Version 11.31
 - Impersonate Version 4.0.3

**Comment by SupianIDz** [comment]
Hi @MCKLtech, there is no such function. If you want to check whether you are in impersonation mode or not, you can use the code below:

```
impersonate()->check();

// or
app('impersonate')->check();

// or
$user->impersonate()->check();
```
