### ISSUE TITLE
LogicError on binary file download

### ISSUE THREAD

**Issue by wh5a** [OctopyID/LaraPersonate#3]
It seems the middleware should ignore binary files. I'm new to PHP and Laravel, so I simply hacked a try-catch in the modify function and it works for now.

The exception is:

LogicException
The content cannot be set on a BinaryFileResponse instance.

**Comment by SupianIDz** [comment]
I'll check it ASAP.

**Comment by SupianIDz** [comment]
@wh5a Hi, it's been fixed, you can update it to the latest released version.
