### ISSUE TITLE
Error Attempted to lazy load [roles] when canBeImpersonated is used

### ISSUE THREAD

**Issue by rahmanramsi** [OctopyID/LaraPersonate#7]
- Impersonate Version: 2.0.8
- Laravel Version: v.8.77.1
- PHP Version: 8.0.13
- Database Driver & Version: Mysql, Ver 14.14 Distrib 5.7.34, for Linux (x86_64)
- Role Manager : spatie/laravel-permission
### Description:
Attempt to lazy load roles when canBeImpersonated() function is added.
![image](https://user-images.githubusercontent.com/48276043/147713019-136efe95-2349-43eb-8c40-3e90c1e0f4b9.png)

### Steps To Reproduce:

1. On `AppServiceProvider`, add code below on boot function to prevent lazy loading on all models.
 ```php
Model::preventLazyLoading(!app()->isProduction());
``` 

2. On model `User`, add code : 
```php
public function canBeImpersonated(): bool
  {
    return !$this->hasRole([Role::SUPER_ADMIN]);
  }
```

Result : 
![image](https://user-images.githubusercontent.com/48276043/147712970-e3c6dad7-855c-439b-a710-2ce4d68e42c7.png)

**Comment by SupianIDz** [comment]
Hi @rahmanramsi , it should be fixed in v2.0.9 release
