### ISSUE TITLE
Auth::user() not showing changed user

### ISSUE THREAD

**Issue by rightwayround** [OctopyID/LaraPersonate#8]
- Impersonate Version: 2.0.9
- Laravel Version: 8.80.0
- PHP Version: 8.1
- Database Driver & Version: mysql

### Description:
The interface shows the user list and I can change user so that it shows that I am impersonating another person BUT... 

```
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\User;
use Illuminate\Support\Facades\Auth;

class CustomReport extends Controller
{
    /**
     * Handle the incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function __invoke(Request $request)
    {
        $user = User::find(Auth::id())->first();
    }
}
```

`$user` doesn't change.

I wonder if I am going the wrong way about getting the current user?

Help appreciated, thanks.

PS. this package looks great, thank you, hope I can use it in practise.

**Comment by SupianIDz** [comment]
@rightwayround 
```php
$user = User::find(Auth::id())->first();
```

It will always return the same $user.


Assumption you data is :

```json
{
  "id": 1,
  "email": "foo@bar.com"
},
{
  "id": 2,
  "email": "bar@bar.com"
}
,
{
  "id": 3,
  "email": "baz@bar.com"
}
```

I assume the user with `id 1` is the authenticated user

```php
Auth::id()

{
  "id": 1,
  "email": "foo@bar.com"
}
```

So

```php
User::find(Auth::id())
# This is the same as

User::find(1)

# And the result always

{
  "id": 1,
  "email": "foo@bar.com"
}
```

From your code snippet above, you include `first()` and it will always result in data in the first row.

If you need logged in `$user` data, you can simply 
```php 
$user = Auth::user()
```

**Comment by rightwayround** [comment]
Hmm sorry I was working late and made a silly mistake, your library is working fine.

Thanks so much.
